version: "3.7"

services: 
    dashboard:
        #container_name: dashboard
        build: ./dashboard
        ports:
            - "3000:3000"
        volumes: 
            - ".:/app"
            - "/app/node_modules"
        environment: 
            - REACT_APP_PORT=3000
        expose:
            - 3000
        ports: 3000:3000
        volumes: 
            - ./dashboard/src:/app/src
            - ./dashboard/public:/app/public
        command: yarn start