version: '3'
services: 
    postgres:
        image: postgres:latest
    dashboard:
        build: 
            context: ./dashboard
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./client:/app
        ports: 
            - '3000:3000'
        restart: on-failure
        container_name: dashboard
    api:
        build: 
            context: ./api
            dockerfile: Dockerfile
        ports: 
            - '3001:3001'
        restart: on-failure
        container_name: api
        volumes: 
            - /app/node_modules
            - ./api:/app
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=
            - PGPORT=5432
