version: '3'
services: 
    postgres:
        image: postgres:latest
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_HOST: 'postgres'
    dashboard:
        build: 
            context: ./dashboard
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./dashboard:/app
        ports: 
            - '3000:3000'
        restart: on-failure
        container_name: dashboard
    api:
        build: 
            context: ./api
            dockerfile: Dockerfile
        ports: 
            - '3001:3001'
        restart: on-failure
        container_name: api
        volumes: 
            - /app/node_modules
            - ./api:/app
